[package]
name = "crates_stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
thiserror = "1.0.56"
walkdir = "2.4.0"